//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PC_ClubEntities5 : DbContext
    {
        private static PC_ClubEntities5 _context;
        public PC_ClubEntities5()
            : base("name=PC_ClubEntities5")
        {
        }

        public static PC_ClubEntities5 GetContext()
        {
            if(_context == null)
            {
                _context = new PC_ClubEntities5();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deliver> Deliver { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Pc> Pc { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Rate> Rate { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
