//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class PC_ClubEntities5 : DbContext
    {
        private static PC_ClubEntities5 _context;
        public PC_ClubEntities5()
            : base("name=PC_ClubEntities5")
        {
        }
        public static PC_ClubEntities5 GetContext()
        {
            if (_context == null)
            {
                _context = new PC_ClubEntities5();
            }
            return _context;
        }

        public List<TariffPopularityResult> GetTopTariffs()
        {
            // LINQ запрос для получения популярных тарифов
            var topTariffs = (from check in this.Receipt
                              join session in this.Session on check.SessionID equals session.SessionID // ID сессии в чеке
                              join tariff in this.Rate on session.RateID equals tariff.RateID   // ID тарифа в сессии
                              group tariff by tariff.RateName // Группируем по названию тарифа
                              into tariffGroup
                              orderby tariffGroup.Count() descending
                              select new TariffPopularityResult
                              {
                                  TariffName = tariffGroup.Key,
                                  UsageCount = tariffGroup.Count()
                              }).ToList();

            return topTariffs;
        }

        public class TariffPopularityResult
        {
            public string TariffName { get; set; }
            public int UsageCount { get; set; }
        }

        public class ProductSalesReport
        {
            public string ProductName { get; set; }
            public int QuantitySold { get; set; }
            public decimal TotalAmount { get; set; }
        }

        public List<ProductSalesReport> GetProductSalesReport()
        {
            var productSales = (from check in this.Receipt
                                join product in this.Product on check.ProductID equals product.ProductID
                                group check by new { product.ProductName, product.ProductPrice } into productGroup
                                select new ProductSalesReport
                                {
                                    ProductName = productGroup.Key.ProductName,
                                    QuantitySold = productGroup.Count(),
                                    TotalAmount = productGroup.Count() * productGroup.Key.ProductPrice
                                }).ToList();

            return productSales;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deliver> Deliver { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Pc> Pc { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Rate> Rate { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
