//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver
    {
        public decimal DeliverID { get; set; }
        public Nullable<decimal> ProviderID { get; set; }
        public Nullable<decimal> ProductID { get; set; }
        public Nullable<decimal> ProductQuantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
