//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public decimal ReciptID { get; set; }
        public Nullable<decimal> SessionID { get; set; }
        public Nullable<decimal> ProductID { get; set; }
        public Nullable<decimal> DiscountID { get; set; }
        public Nullable<decimal> Sum { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Product Product { get; set; }
        public virtual Session Session { get; set; }
    }
}
