//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public decimal ReviewID { get; set; }
        public decimal UserID { get; set; }
        public decimal Rating { get; set; }
        public string Message { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
